### ISSUE TITLE
No indicator possible (no options under calculation type) (Netflix data)

### ISSUE THREAD

**Issue by Lisa-Stamm** [Explorama/Explorama#38]
<img width="373" alt="image" src="https://github.com/Explorama/Explorama/assets/138019440/f2b1951d-9ab5-4418-9fa9-1e2021b6b851">

browser

**Comment by sstoehrm** [comment]
Fixed in [v1.0.0-alpha.2](https://github.com/Explorama/Explorama/releases/tag/v1.0.0-alpha.2)
