### ISSUE TITLE
roadmap data has no layout, although it should be in range

### ISSUE THREAD

**Issue by Lisa-Stamm** [Explorama/Explorama#42]
<img width="516" alt="image" src="https://github.com/Explorama/Explorama/assets/138019440/9afdbe43-65ba-46f9-9c6c-e1b745d660e5">

**Comment by sstoehrm** [comment]
Fixed in [v1.0.0-alpha.2](https://github.com/Explorama/Explorama/releases/tag/v1.0.0-alpha.2)
