### ISSUE TITLE
Importer: i cannot change the type (YYYY-MM-dd) of a date, i need YYYY

### ISSUE THREAD

**Issue by Lisa-Stamm** [Explorama/Explorama#44]
Importer: i cannot change the type (YYYY-MM-dd) of a date, i need YYYY
FYI: Import failed also when i deactivate date and it gets theoretically automatically created

**Comment by Lisa-Stamm** [comment]
![image](https://github.com/Explorama/Explorama/assets/138019440/04b21705-794b-4688-8b76-663d6c657e8a)

**Comment by sstoehrm** [comment]
Fixed with [commit](https://github.com/Explorama/Explorama/commit/5e6b503ec9f2583bca9df97aca2448a418f2fb09)
